baseURL: https://nixos-options.extranix.com/
languageCode: en-us
title: NixOS - Option Search
theme: extranix-options-search

params:

  release_switch_title: NixOS Release
  releases:
    - name: unstable
      value: release-unstable
    - name: 23.11
      value: release-23.11
    - name: 23.05
      value: release-23.05
    - name: 22.11
      value: release-22.11

  xcustom_head_scripts: |
    <script async src="https://umami.pimsnel.com/script.js" data-website-id="8e970d59-b517-4ba6-9b92-207e7dbdb4b1"></script>
    <script async src="https://media.ethicalads.io/media/client/ethicalads.min.js"></script>

  xcustom_header_tags: <div id="eadiv" data-ea-publisher="extranixcom" data-ea-type="text"></div>

  footer_credits_line: |
    Powered by the <a href="https://nixos.org/">NixOS</a> |
    <a href="https://github.com/mipmip/home-manager-option-search#credits">Credits</a> |
    <a href="https://nixos.org/manual/nixos/stable/">NixOS Documentation</a>

  footer_copyright_line: |
    Made with ❤️ by <a href="https://github.com/mipmip">Pim Snel</a> - © 2024

  xlogo: images/home-manager-option-search2.png

  xgithub:
    repo: nixos-option-search
    user: mipmip
    show_count: true
    show_text: true

  main_menu:

    - name: NixOS&nbsp;Documentation
      url: https://nixos.org/manual/nixos/stable/
      icon_class: fa fa-book

    - name: Source
      url: https://github.com/mipmip/nixos-option-search
      icon_class: fa fa-github

markup:
  goldmark:
    renderer:
      unsafe: true
