name: "parse and deploy"
on:
  schedule:
    - cron:  '05 4 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: parse options and create search
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: extract-options-release-unstable
        env:
          RELEASE: unstable
        run: ./scripts/build_options.sh

      #      - name: extract-options-release-23.11 (stable)
      #        env:
      #          RELEASE: "23.11"
      #        run: ./scripts/build_options.sh

      - name: Build Hugo
        run: nix run nixpkgs#hugo -- --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-${{ github.ref_name }}
          publish_dir: ./public
